# fly.toml app configuration file generated for smasher-api on 2025-10-07T02:08:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smasher-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  # Removed deprecated processes field

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health/live'

# Removed legacy [[services]] block to avoid conflicts with http_service

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
