services:
  - type: web
    name: smasher-api
    env: node
    rootDir: server
    repo: https://github.com/honkyhank82/Smasher
    branch: master
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase: smasher-db
      - key: STRIPE_SECRET_KEY
        fromSecret: stripe_secret_key
      - key: STRIPE_WEBHOOK_SECRET
        fromSecret: stripe_webhook_secret
      - key: STRIPE_PRICE_ID
        value: price_1SNBIbCKpcCZj0lLEYh12CC5
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: RESEND_API_KEY
        fromSecret: resend_api_key
      - key: FROM_EMAIL
        value: noreply@smasher.app
      - key: R2_ACCOUNT_ID
        fromSecret: r2_account_id
      - key: R2_ACCESS_KEY_ID
        fromSecret: r2_access_key_id
      - key: R2_SECRET_ACCESS_KEY
        fromSecret: r2_secret_access_key
      - key: R2_BUCKET_NAME
        value: smasher-media
      - key: R2_PUBLIC_URL
        value: https://r2.smasher.app
    
    healthCheckPath: /health
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    
    domains:
      - smasher.onrender.com
    
    resources:
      cpu: 500m
      memory: 512MB
      disk: 1GB
    
    autoDeploy: true
    
    # Node runtime does not require explicit Docker volumes

databases:
  - name: smasher-db
    databaseName: smasher
    plan: standard
    postgresVersion: "14"