#!/bin/bash
set -e

echo "Starting APK build process..."

# Navigate to app-rn
cd app-rn

echo "Installing app dependencies..."
npm install

echo "Environment check:"
node -v
npm -v
echo "JAVA_HOME: $JAVA_HOME"
echo "ANDROID_HOME: $ANDROID_HOME"

# Create local.properties for Android build
if [ -n "$ANDROID_HOME" ]; then
    echo "Creating local.properties with sdk.dir=$ANDROID_HOME"
    echo "sdk.dir=$ANDROID_HOME" > android/local.properties
fi

echo "Building APK locally to bypass cloud limits..."
# Check if running on Windows
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    echo "WARNING: Running on Windows environment."
    # We allow building on Windows if the user has setup the environment, 
    # but in CI/CD (GitHub Actions), it runs on Linux/Mac usually.
    # If this script is running in Git Bash on Windows, it's fine.
    # The warning below was too aggressive.
fi

# Run EAS build locally using npx to ensure CLI availability
# Using --yes to suppress installation prompts
echo "Running EAS build..."

# Clean previous builds
rm -rf ../build
mkdir -p ../build

# Sync native files with app.json (version, versionCode, etc.)
# This ensures build.gradle gets the updated version
echo "Syncing native files..."
npx expo prebuild --platform android --no-install --clean

# Ensure gradlew is executable (it might be regenerated by prebuild)
if [ -f "android/gradlew" ]; then
    chmod +x android/gradlew
fi

npx --yes eas-cli build --local --platform android --profile production-apk --non-interactive --output ../build/app.apk --clear-cache

echo "Build completed."
if [ -f "../build/app.apk" ]; then
    echo "APK generated successfully."
    ls -l ../build/app.apk
else
    echo "APK file not found - build was skipped or failed"
    ls -l ../build/
    exit 1
fi
